@startuml
/'
Author: Udinei Silva
This file defines the architecture of the uKalicoBaseTest framework. 
To graphically visualize the architecture, copy and paste the code from this file on the website: http://www.plantuml.com/plantuml/uml/
'/
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/devicons/go.puml

AddRelTag("async", $lineStyle = DashedLine())


SHOW_PERSON_PORTRAIT()

Person(analista,"Analista","Analisa caso de testes")
Person(desenvolvedor,"Desenvolvedor","Desenvolve caso de testes")

System_Ext(ide,"Intellij","Mantém Analisa Entrada/Saída/Executa/Verificação")

System_Ext(myapp,"MyApp","Executa Funcionalidade/Validação", "teste")
System_Ext(browser,"Browser","Carrega App e Input/Output dados")

ContainerDb(bd,"Banco de dados","BD","Armazena dados/Executa regras negocios")

System_Boundary(framework, "FrameWork UkBaseTest"){


Container(webdriver,"WebDriver","Selenium WebDriver","Controla o Browser")
Container(grid,"Grid","Selenium Grid","Testes em Grid")
ContainerQueue(screenshot,"Disco","HD","Salva screenshot dos testes")
Container(core,"Core","Framework UkbaseTeste/Java","Controla e executa os testes")
Container(projeto_teste,"Projeto Teste","Projeto de testes Myapp","Implementa os testes do sistema/Java/Junit/Maven")
Container(surefire,"Surefire","maven-surefire-plugin","Executa os testes em paralelo")



Rel(analista, ide,"Codifica","IDE")
Rel(desenvolvedor, ide,"Codifica","IDE")
Rel(webdriver, browser, " ")
Rel(ide, projeto_teste,"mantém")
Rel(ide, framework,"executa")
Rel(core, screenshot, "img",$tags = "async", jpg)
Rel(browser,myapp," ")
Rel(browser,webdriver," ")
Rel(myapp,browser," ")
Rel(myapp,bd,"Input")
Rel(bd,myapp,"Output")
Rel(core,webdriver,"input")
Rel(webdriver,core,"output ")
Rel(core,projeto_teste,"executa")
Rel(core,grid,"executa")
Rel(framework,ide,"Status do teste Falha/Sucesso")
Rel(core, surefire,"executa")
}
@enduml
